config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :audios, only: [ :create, :index ]
  resources :slides, only: [ :create, :index, :show ]
  resources :images
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "slides#index"
end

app/models/slide.rb
class Slide < ApplicationRecord
  has_many :parts, dependent: :destroy
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  def index
    redirect_to Slide.first
  end

  def show
    @slide = Slide.find(params[:id])

    @slide_next = Slide.where("id > ?", @slide.id).order(id: :asc).first
    @slide_prev = Slide.where("id < ?", @slide.id).order(id: :desc).first
  end
end

app/views/slides/_header.html.erb
<div class="w-full h-auto text-xl md:text-8xl font-semibold"><%= contents.html_safe %></div>

app/views/slides/_slide.html.erb
<% if slide.title.present? %>
  <%= render partial: 'header', locals: { contents: slide.title } %>
<% end %>

<%= render slide.parts %>

app/views/slides/show.html.erb
<div class="w-full h-full font-normal overflow-hidden bg-black" data-controller="threejs">
  <turbo-frame id="slide">
    <div class="slide bg-background absolute top-0 right-0 left-0 bottom-0 p-6 md:px-24 md:py-14">
      <%= render @slide %>
    </div>
  </turbo-frame>
  <div class=""></div>
  <div class="class flex justify-between">
    <% if @slide_prev %>
      <a href="<%= slide_path(@slide_prev) %>"
        data-controller="slides"
        data-action="keydown.n@window->slides#click keydown.page_up@window->slides#click"
      >
        <<
      </a>
    <% else %>
      <div></div>
    <% end %>

    <% if @slide_next %>
      <a href="<%= slide_path(@slide_next) %>"
        data-controller="slides"
        data-action="keydown.m@window->slides#click keydown.page_down@window->slides#click"
      >
        >>
      </a>
    <% else %>
      <div></div>
    <% end %>
  </div>

  <div data-controller="audioindex">
    <div>
      <button type="button" class="invisible" data-action="keydown.r@window->audioindex#startRecording" ></button>
      <button type="button" class="invisible" data-action="keydown.t@window->audioindex#stopRecording"></button>
      <button type="button" class="invisible" data-action="keydown.tab@window->audioindex#toggleRecording"></button>
    </div>
  </div>

  <div id="audios"></div>
  <%= turbo_stream_from "audios" %>
</div>
<div id="debug" class="hidden absolute top-0 bottom-0 right-0 w-12 flex flex-col bg-gray-100 items-center justify-center gap-2">
  <div class="w-8 h-8 bg-black rounded-full" id="recordingIndicator"></div>
  <div class="w-8 h-8 bg-green-500 rounded-full" id="otherIndicator"></div>
</div>