config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :audios, only: [ :create, :index ]
  resources :slides, only: [ :create, :index, :show ]
  resources :images
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "slides#index"
end

app/models/image.rb
class Image < ApplicationRecord
  has_one_attached :file

  has_neighbors :embedding
  after_create_commit :broadcast
  after_create_commit -> { ImageRecalculateEmbeddingJob.perform_later(id) }

  def broadcast
    Turbo::StreamsChannel.broadcast_append_later_to(
      "images",
      target: "images",
      partial: "images/image",
      locals: {
        image: self
      }
    )
  end

  def recalculate_embedding
    return unless file.attachment.present?

    base64_encoded_image = Base64.strict_encode64(file.download)

    messages = [
      { "type": "text", "text": "What’s in this image? Do not identify people, just describe them and their surroundings. If possible - include gender, clothing and color description." },
      { "type": "image_url",
        "image_url": {
          "url": "data:image/png;base64,#{base64_encoded_image}"
        }
      }
    ]

    response = OpenAIClient.chat(
      parameters: {
        model: "gpt-4o-mini",
        messages: [ { role: "user", content: messages } ]
      }
    )

    self.description = response.dig("choices", 0, "message", "content")

    response = OpenAIClient.embeddings(
      parameters: {
        model: "text-embedding-3-large",
        input: description
      }
    )
    self.embedding = response.dig("data", 0, "embedding")
    self.save
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[ show edit update destroy ]

  # GET /images or /images.json
  def index
    if params[:query].present?
      client = OpenAI::Client.new(access_token: Rails.configuration.x.openai_api_key)

      embedding = client
        .embeddings(parameters: { model: "text-embedding-3-large", input: params[:query] })
        .dig("data", 0, "embedding")

      @images = Image.nearest_neighbors(:embedding, embedding, distance: "euclidean").first(1)
    else
      @images = Image.all
    end
  end

  # GET /images/1 or /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images or /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to :images, notice: "Image was successfully created." }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: "Image was successfully updated." }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    @image.destroy!

    respond_to do |format|
      format.html { redirect_to images_path, status: :see_other, notice: "Image was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.expect(image: [ :file ])
    end
end

app/views/images/_form.html.erb
<div data-controller="imagecreate">
  <%= form_with(model: image) do |form| %>
    <% if image.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

        <ul>
          <% image.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :file, style: "display: block" %>
      <%= form.file_field :file %>
    </div>

    <button type="submit" class="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700 transition-colors">
      Save
    </button>
  <% end %>
</div>

app/views/images/_image.html.erb
<% background ||= "" %>

<div class="p-2 <%= background %>">
  <%= image_tag(url_for(image.file), id: dom_id(image)) %>
</div>

app/views/images/_take_a_selfie.html.erb
<div class="w-full h-full pt-0 md:pt-12 flex flex-col items-center justify-start font-normal bg-background" data-controller="imagecreate">
  <div class="selfie-container mt-12 items-center flex flex-col">
    <button class="selfie-startbutton mb-8 text-center w-full bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors">
      Click here to take a photo
    </button>

    <select id="videoSource" class="mb-8 text-center w-full px-4 py-2 rounded-lg">
    </select>

    <video class="selfie-video rounded-xl border-2 shadow-lg">
      Video stream not available.
    </video>

    <div class="loading-mask hidden absolute top-0 bottom-0 left-0 right-0 opacity-75 bg-gray-400 flex justify-center items-center">
      <div role="status">
        <svg aria-hidden="true" class="w-20 h-20 text-gray-200 animate-spin dark:text-gray-600 fill-blue-600" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor"/>
            <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill"/>
        </svg>
        <span class="sr-only">Loading...</span>
      </div>
    </div>
  </div>
</div>

app/views/images/edit.html.erb
<% content_for :title, "Editing image" %>

<h1>Editing image</h1>

<%= render "form", image: @image %>

<br>

<div>
  <%= link_to "Show this image", @image %> |
  <%= link_to "Back to images", images_path %>
</div>

app/views/images/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Images" %>

<h1>Images</h1>
<%= link_to "Upload new image", new_image_path %>

<hr>

<div>
  <%= form_with url: "/", method: :get do |form| %>
    <%= form.label :query, "Search for:" %>
    <%= form.text_field :query, value: params[:query] %>
    <%= form.submit "Search" %>
  <% end %>
  <% if params[:query].present? %>
    <%= link_to "Clear Search", root_path %>
  <% end %>
</div>

<div id="images" style="margin-top: 20px;">
  <% @images.each do |image| %>
    <%= render image %>
  <% end %>
</div>

app/views/images/new.html.erb
<%= render partial: 'take_a_selfie' %>

app/views/images/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @image %>

<div>
  <%= link_to "Edit this image", edit_image_path(@image) %> |
  <%= link_to "Back to images", images_path %>

  <%= button_to "Destroy this image", @image, method: :delete %>
</div>